### PR TITLE
Use our Now() instead of time.Now()

### PR DESCRIPTION
**Pull request by hnakamur**
`Now` was introduced at commit https://github.com/go-graphite/go-whisper/pull/1/commits/86a100a8a02a426da5cd13cbbb23255d26bb6832, but two occurrences of `time.Now` remains.
This pull request replaces these two `time.Now()` with `Now()`.

### CODE REVIEW

**Comment by bom-d-van** [comment]
LGTM. Thanks for your contributions. :)

**Comment by deniszh** [comment]
Will try to fix builds, though

**Comment by bom-d-van** [comment]
@deniszh Thanks.
Looks like it's because it's because I put all the commands in one dir `cmd`. Maybe putting `// +build ignore` in all the cmd/*.go could resolve the issue in Travis CI.

**Comment by deniszh** [comment]
Yes, you was absolutely right, @bom-d-van ! I also changed go versions to supported + master - build is green now.

**Pull request merged**
