### PR TITLE
Add "First" aggregation

### PR DESCRIPTION
**Pull request by korservick**
Useful for OHLC store (https://en.wikipedia.org/wiki/Open-high-low-close_chart)

### CODE REVIEW

**Comment by bom-d-van** [comment]
@korservick I was thinking about it in the past, but I think the reason graphite doesn't have a first aggregation policy is because there is already a last aggregation policy, and first and last is only one data point apart so for time series data, they most likely deliver similar end results. 

But I'm not sure if this logic could be applied on stock data.

@deniszh @azhiltsov @Civil what do you think?

**Comment by Civil** [comment]
My opinion is that Whisper library should support all aggregation policies that graphite-web and carbonapi supports in their functions. Which actually includes "last" as well.

**Comment by deniszh** [comment]
@Civil: but  "last" is already there, this PR is about to include "first", which is new. Or I misunderstand something?
I'm not against that small addition, though

**Comment by Civil** [comment]
I mean that aggregation functions in graphite have both last and first. So if it's useful there, it should be useful (for some one) in whisper as well.

**Comment by deniszh** [comment]
Ah, make sense.

**Comment by bom-d-van** [comment]
@Civil From the doc, there is no first aggregation policy?
https://graphite.readthedocs.io/en/latest/whisper.html#rollup-aggregation

**Comment by Civil** [comment]
My point was that whatever supported for https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.consolidateBy should be available as rollup aggregation for whisper.

**Comment by bom-d-van** [comment]
Yep, I updated my comment above. No objection of merging it. :)

**Comment by korservick** [comment]
> @korservick I thought about this in the past, but I think the reason graphite doesn't have a first aggregation policy is because there is already a last aggregation policy, and first and last is only one data point apart so for time series data, they most likely deliver similar end results.
> 
> But I'm not sure if this logic could be applied on stock data.

For stock data it is sensible for the Open(First) and Close(Last) data which aggregation method to chose. Close in one period almost never be equal Open in next period. And yeah, it is only one data point in all aggregation period (First and Last).

So thats why I add this small PR :)

**Pull request merged**
